#!/bin/sh
# Script intended to initialize and start the local server
# It leverages a podman pod so serve external services needed.

# Setup the dependencies pod to be used by the server

HERE_PATH="$(dirname $(realpath $0))"
DEPS_POD_YAML="$HERE_PATH/deps-pod.yaml"

POD_STATUS=$(podman pod list | grep portifolio-deps)

if echo $POD_STATUS | grep -q "Running"; then
    echo "deps-pod: running"
elif echo $POD_STATUS | grep -q "Exited"; then
    echo "deps-pod: starting"
    podman pod start portifolio-deps >/dev/null
    sleep 1 # let it start the pod in peace, cmon
else
    echo "deps-pod: creating"
    podman play kube "$(dirname $(realpath $0))/deps-pod.yaml" >/dev/null
    sleep 1 # let it play the kube in peace, geez
fi

# Run the server with required environment variables

(export $(cat "$HERE_PATH/.env") && cargo run)
